os: Visual Studio 2019
platform: x64


environment:
  matrix:
    
    - job_name: Microsoft Visual C++
      compiler: msvc-16-seh
      generator: "Visual Studio 16 2019"
      build_system: cmake
      
    - job_name: MinGW  
      compiler: gcc-8.1.0-posix
      build_system: cmake
      generator: "MinGW Makefiles"
      cxx_path: 'C:\mingw-w64\i686-8.1.0-posix-dwarf-rt_v6-rev0\mingw32\bin'

    - job_name: WSL GCC
    
    - job_name: WSL Clang


for:
  -
    matrix:
      only:
        - job_name: Microsoft Visual C++
    build_script:
    - ps: |
        md build
        cd build
        cmake -G $env:generator -A x64 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS_DEBUG=" /bigobj " -DPARLAY_TEST=On ..
        cmake --build .
        ctest -C Debug --no-tests=error --output-on-failure
  
  -
    matrix:
      only:  
        - job_name: MinGW
    build_script:
    - ps: |
        md build
        cd build
        $env:path = $env:path.replace("C:\Program Files\Git\usr\bin;", "")
        $env:path += ";$env:cxx_path"
        cmake -G $env:generator -DCMAKE_BUILD_TYPE=Debug -DPARLAY_TEST=On ..
        cmake --build .
        ctest -C Debug --no-tests=error --output-on-failure
    
  -
    matrix:
      only:          
        - job_name: WSL GCC
    install:
    - ps: |
        wsl sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        wsl sudo apt-get -qq update
        wsl sudo apt-get -y install gcc-9 g++-9 make
        wsl wget --quiet https://github.com/Kitware/CMake/releases/download/v3.18.2/cmake-3.18.2-Linux-x86_64.tar.gz
        wsl tar -xf cmake-3.18.2-Linux-x86_64.tar.gz
    build_script:
    - ps: |
        md build
        cd build
        wsl CC=gcc-9 CXX=g++-9 ../cmake-3.18.2-Linux-x86_64/bin/cmake -DCMAKE_BUILD_TYPE=Debug -DPARLAY_TEST=On -DWSL=True ..
        wsl make
        wsl ../cmake-3.18.2-Linux-x86_64/bin/ctest -C Debug --no-tests=error --output-on-failure
        
  -
    matrix:
      only:          
        - job_name: WSL Clang
    install:
    - ps: |
        wsl sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        wsl sudo apt-get -qq update
        wsl sudo apt-get -y install gcc-9 g++-9 clang-10 make
        wsl wget --quiet https://github.com/Kitware/CMake/releases/download/v3.18.2/cmake-3.18.2-Linux-x86_64.tar.gz
        wsl tar -xf cmake-3.18.2-Linux-x86_64.tar.gz
    build_script:
    - ps: |
        md build
        cd build
        wsl CC=clang-10 CXX=clang++-10 ../cmake-3.18.2-Linux-x86_64/bin/cmake -DCMAKE_BUILD_TYPE=Debug -DPARLAY_TEST=On -DWSL=True ..
        wsl make
        wsl ../cmake-3.18.2-Linux-x86_64/bin/ctest -C Debug --no-tests=error --output-on-failure
