name: Build
on: [push, pull_request]
env:
  PARLAY_NUM_THREADS: 16

jobs:
  build:
    name: ${{ matrix.config.os }} ${{ matrix.config.cxx }} ${{ matrix.config.note }} (${{ matrix.build_type }})
    runs-on: ${{ matrix.config.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        build_type: ["Debug", "RelWithDebInfo", "Release"]
        config:
          - {
            os: ubuntu-latest,
            cc: "gcc-7", cxx: "g++-7"
          }
          - {
            os: ubuntu-latest,
            cc: "gcc-11", cxx: "g++-11"
          }
          - {
            os: ubuntu-18.04,
            cc: "clang-6.0", cxx: "clang++-6.0"
          }
          - {
            os: ubuntu-latest,
            cc: "clang-12", cxx: "clang++-12"
          }
          - {
            os: ubuntu-latest,
            cc: "clang-10", cxx: "clang++-10",
            libcxx: true,
            libcxx_version: 10,
            note: " with libc++"
          }
          - {
            os: macos-latest,
            cc: "gcc-11", cxx: "g++-11"
          }
          - {
            os: macos-latest,
            cc: "clang", cxx: "clang++"
          }

    steps:
      - uses: actions/checkout@v2

      - name: Set up toolchain repositories
        if: ${{ matrix.config.os == 'ubuntu-18.04' }}
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-6.0 main"

      - name: Install Compiler
        if: startsWith(matrix.config.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get -qq install ${{matrix.config.cc}} ${{matrix.config.cxx}}

      - name: Install libc++
        if: matrix.config.libcxx
        run: sudo apt-get -qq install libc++1-${{matrix.config.libcxx_version}} libc++abi1-${{matrix.config.libcxx_version}} libc++-${{matrix.config.libcxx_version}}-dev libc++abi-${{matrix.config.libcxx_version}}-dev

      - name: Configure
        run: |
          mkdir build && cd build
          CC=${{matrix.config.cc}} CXX=${{matrix.config.cxx}} cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DPARLAY_TEST=On -DPARLAY_BENCHMARK=On -DPARLAY_EXAMPLES=On -DUSE_LIBCXX=${{matrix.config.libcxx}} ..

      - name: Build
        run: |
          cd build
          make

      - name: Test
        run: |
          cd build
          ctest --no-tests=error --output-on-failure

  msvc:
    name: windows-latest MSVC 19 (${{matrix.build_type}})
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: ["Debug", "RelWithDebInfo", "Release"]
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Configure
        run: |
          md build
          cd build
          cmake -A x64 -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_FLAGS=" /bigobj " -DPARLAY_TEST=On -DPARLAY_BENCHMARK=On -DPARLAY_EXAMPLES=On ..

      - name: Build
        run: |
          cd build
          cmake --build .

      - name: Test
        run: |
          cd build
          ctest -C Debug --no-tests=error --output-on-failure

  wsl:
    strategy:
      matrix:
        config:
          - { cc: "gcc-11", cxx: "g++-11" }
          - { cc: "clang-12", cxx: "clang++-12" }

    name: windows-2019 WSL ${{ matrix.config.cxx }} (Debug)
    runs-on: windows-2019
    defaults:
      run:
        shell: wsl-bash {0}
    steps:
      - uses: actions/checkout@v2
      - uses: Vampire/setup-wsl@v1
        with:
          distribution: Ubuntu-20.04

      - name: Install
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt-get -qq update
          sudo apt-get -y install make ${{matrix.config.cc}} ${{matrix.config.cxx}}
          wget --quiet https://github.com/Kitware/CMake/releases/download/v3.18.2/cmake-3.18.2-Linux-x86_64.tar.gz
          tar -xf cmake-3.18.2-Linux-x86_64.tar.gz

      - name: Configure
        run: |
          mkdir build
          cd build
          CC=${{matrix.config.cc}} CXX=${{matrix.config.cxx}} ../cmake-3.18.2-Linux-x86_64/bin/cmake -DCMAKE_BUILD_TYPE=Debug -DPARLAY_TEST=On -DPARLAY_BENCHMARK=On -DPARLAY_EXAMPLES=On -DWSL=True ..

      - name: Build
        run: |
          cd build
          make

      - name: Test
        run: |
          cd build
          ../cmake-3.18.2-Linux-x86_64/bin/ctest -C Debug --no-tests=error --output-on-failure

#  msys:
#    strategy:
#      matrix:
#        include:
#          - { sys: mingw64 }
#          - { sys: ucrt64 }
#          - { sys: clang64 }
#
#    name: windows-latest MSYS2 ${{ matrix.sys }} (Debug)
#    runs-on: windows-latest
#    defaults:
#      run:
#        shell: msys2 {0}
#    steps:
#      - uses: actions/checkout@v2
#      - name: '${{ matrix.icon }} Setup MSYS2'
#        uses: msys2/setup-msys2@v2
#        with:
#          msystem: ${{matrix.sys}}
#          update: true
#          install: >-
#            git
#            make
#          pacboy: >-
#            toolchain:p
#            cmake:p
#            ninja:p
#
#      - name: Configure
#        run: |
#          mkdir build
#          cd build
#          cmake -DCMAKE_BUILD_TYPE=Debug -DPARLAY_TEST=On -DPARLAY_BENCHMARK=On -DPARLAY_EXAMPLES=On ..
#
#      - name: Build
#        run: |
#          cd build
#          cmake --build .
#
#      - name: Test
#        run: |
#          cd build
#          ctest -C Debug --no-tests=error --output-on-failure

  cygwin:
    strategy:
      matrix:
        config:
          - { cc: "gcc", cxx: "g++" }
          - { cc: "clang", cxx: "clang++" }

    name: windows-latest Cygwin ${{ matrix.config.cxx }} (Debug)
    runs-on: windows-latest
    defaults:
      run:
        shell: C:\tools\cygwin\bin\bash.exe -eo pipefail -o igncr '{0}'
    steps:
      - uses: actions/checkout@v2
      - uses: egor-tensin/setup-cygwin@v3
        with:
          packages: git,make,gcc-core,gcc-g++,cmake,clang,libiconv-devel,cygwin32-libiconv-1.14-2

      # Note: The benchmarks are currently not compiled on Cygwin because Google Benchmark's CMake configuration fails for some reason...
      - name: Configure
        run: |
          mkdir build
          cd build
          CC=${{matrix.config.cc}} CXX=${{matrix.config.cxx}} cmake -DCMAKE_BUILD_TYPE=Debug -DPARLAY_TEST=On -DPARLAY_EXAMPLES=On ..

      - name: Build
        run: |
          cd build
          make

      - name: Test
        run: |
          cd build
          ctest -C Debug --no-tests=error --output-on-failure

  cilk-plus:
    name: ubuntu-18.04 Cilk Plus GCC-7 (Debug)
    runs-on: ubuntu-18.04   # Note: GCC-7 on Ubuntu-20 removed Cilk Plus, so we have to go back in time
    steps:
      - uses: actions/checkout@v2

      - name: Install GCC-7
        shell: bash
        run: |
          sudo apt-get -qq install gcc-7 g++-7

      - name: Configure
        shell: bash
        run: |
          mkdir build && cd build
          CC=gcc-7 CXX=g++-7 cmake -DCMAKE_BUILD_TYPE=Debug -DPARLAY_TEST=On -DPARLAY_NO_TEST_SCHEDULER=True -DCMAKE_CXX_FLAGS="-fcilkplus -DPARLAY_CILKPLUS" -DCMAKE_EXE_LINKER_FLAGS="-fcilkplus -ldl" -DPARLAY_BENCHMARK=On -DPARLAY_EXAMPLES=On ..

      - name: Build
        shell: bash
        run: |
          cd build
          make

      - name: Test
        shell: bash
        run: |
          cd build
          ctest --no-tests=error --output-on-failure

  opencilk:
    name: ubuntu-latest Open Cilk Clang 12 (Debug)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install OpenCilk
        shell: bash
        run: |
          sudo apt-get -qq install gcc-7 g++-7
          git clone https://github.com/OpenCilk/cilkrts.git
          mkdir cilkrts/build && pushd cilkrts/build
          cmake -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_CXX_COMPILER=g++-7 -DCMAKE_INSTALL_PREFIX=/usr/local/ ..
          make && sudo make install
          popd
          wget --quiet https://github.com/OpenCilk/opencilk-project/releases/download/opencilk%2Fv1.1/OpenCilk-1.1-LLVM-12.0.0-Ubuntu-20.04-x86_64.tar.gz
          tar -xf OpenCilk-1.1-LLVM-12.0.0-Ubuntu-20.04-x86_64.tar.gz

      - name: Configure
        shell: bash
        run: |
          mkdir build && cd build
          cmake -DCMAKE_C_COMPILER=$PWD/../OpenCilk-12.0.0-Linux/bin/clang -DCMAKE_CXX_COMPILER=$PWD/../OpenCilk-12.0.0-Linux/bin/clang++ -DCMAKE_BUILD_TYPE=Debug -DPARLAY_TEST=On -DPARLAY_NO_TEST_SCHEDULER=True -DCMAKE_CXX_FLAGS="-fopencilk -DPARLAY_OPENCILK" -DCMAKE_EXE_LINKER_FLAGS="-fopencilk -ldl" -DPARLAY_BENCHMARK=On -DPARLAY_EXAMPLES=On ..

      - name: Build
        shell: bash
        run: |
          cd build
          make

      - name: Test
        shell: bash
        run: |
          cd build
          ctest --no-tests=error --output-on-failure

  tbb:
    name: ubuntu-latest TBB Clang 11 (Debug)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install TBB
        shell: bash
        run: |
          sudo apt-get -qq install clang-11 libtbb-dev

      - name: Configure
        shell: bash
        run: |
          mkdir build && cd build
          CC=clang-11 CXX=clang++-11 cmake -DCMAKE_BUILD_TYPE=Debug -DPARLAY_TEST=On -DPARLAY_NO_TEST_SCHEDULER=True -DCMAKE_CXX_FLAGS="-DPARLAY_TBB" -DCMAKE_EXE_LINKER_FLAGS="-ltbb" DPARLAY_BENCHMARK=On -DPARLAY_EXAMPLES=On ..

      - name: Build
        shell: bash
        run: |
          cd build
          make

      - name: Test
        shell: bash
        run: |
          cd build
          ctest --no-tests=error --output-on-failure

  cppcheck:
    name: Cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Cppcheck
        shell: bash
        run: |
          sudo apt-get -qq install clang-10
          wget --quiet https://github.com/danmar/cppcheck/archive/refs/tags/2.6.tar.gz
          tar -xf 2.6.tar.gz
          mkdir cppcheck-2.6/build && pushd cppcheck-2.6/build
          CC=clang-10 CXX=clang++-10 cmake .. -DCMAKE_BUILD_TYPE=Release
          make && sudo make install
          popd

      - name: Run Cppcheck
        shell: bash
        run: |
          mkdir build && cd build
          CC=clang-10 CXX=clang++-10 cmake -DENABLE_CPPCHECK=On ..
          make cppcheck-all

  clang-tidy:
    name: Clang Tidy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Intall Clang Tidy
        shell: bash
        run: |
          sudo apt-get -qq install clang-10 clang-tidy-10

      - name: Run Clang Tidy
        shell: bash
        run: |
          mkdir build
          cd build
          CC=clang-10 CXX=clang++-10 cmake -DENABLE_CLANG_TIDY=On -DCLANG_TIDY_EXE=/usr/bin/clang-tidy-10 ..
          make clang-tidy-all

  iwyu:
    name: Include-what-you-use
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install IWYU
        shell: bash
        run: |
          sudo apt-get -qq install clang-10 libc++1-10 libc++-10-dev libc++abi1-10 libc++abi-10-dev llvm-10-dev libclang-10-dev
          git clone https://github.com/include-what-you-use/include-what-you-use.git
          mkdir include-what-you-use/build && pushd include-what-you-use/build
          git checkout clang_10
          cmake -DCMAKE_PREFIX_PATH=/usr/lib/llvm-10 ..
          make && sudo make install
          popd

      - name: Run IWYU
        shell: bash
        run: |
          mkdir build
          cd build
          CC=clang-10 CXX=clang++-10 cmake -DENABLE_IWYU=On ..
          make iwyu-all

  asan:
    name: ubuntu-latest ASAN Clang 10 (Debug)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        shell: bash
        run: |
          sudo apt-get -qq install clang-10 libc++1-10 libc++abi1-10 libc++-10-dev libc++abi-10-dev

      - name: Configure
        shell: bash
        run: |
          mkdir build && cd build
          CC=clang-10 CXX=clang++-10 cmake -DCMAKE_BUILD_TYPE=Debug -DPARLAY_TEST=On -DBUILD_ASAN_TESTS=On -DBUILD_ONLY_SANITIZED=True -DUSE_LIBCXX=True ..

      - name: Build
        shell: bash
        run: |
          cd build
          make

      - name: ASAN
        shell: bash
        run: |
          cd build
          ctest --no-tests=error --output-on-failure -R asan

  ubsan:
    name: ubuntu-latest UBSAN Clang 10 (Debug)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        shell: bash
        run: |
          sudo apt-get -qq install clang-10 libc++1-10 libc++abi1-10 libc++-10-dev libc++abi-10-dev

      - name: Configure
        shell: bash
        run: |
          mkdir build && cd build
          CC=clang-10 CXX=clang++-10 cmake -DCMAKE_BUILD_TYPE=Debug -DPARLAY_TEST=On -DBUILD_UBSAN_TESTS=On -DBUILD_ONLY_SANITIZED=True -DUSE_LIBCXX=True ..

      - name: Build
        shell: bash
        run: |
          cd build
          make

      - name: UBSAN
        shell: bash
        run: |
          cd build
          ctest --no-tests=error --output-on-failure -R ubsan

  coverage:
    name: Test Coverage
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Install LCov
        shell: bash
        run: |
          sudo apt-get -qq install gcc-9 g++-9 lcov

      - name: Configure
        shell: bash
        run: |
          mkdir build && cd build
          CC=gcc-9 CXX=g++-9 cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS_DEBUG=" --coverage " -DPARLAY_TEST=On ..

      - name: Build
        shell: bash
        run: |
          cd build
          make

      - name: Test
        shell: bash
        run: |
          cd build
          make check

      - name: Report coverage
        shell: bash
        run: |
          lcov --directory . --capture --output-file coverage.info
          lcov --remove coverage.info '/usr/*' '*/googletest/*' '*/test/*' --output-file coverage.info
          lcov --list coverage.info
          bash <(curl -s https://codecov.io/bash) -f coverage.info
